name: ci
on:
  push:
    branches: [main]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: |
          which cargo
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.56.1
      - run: |
          which cargo
          ls /usr/share
