name: ci
on:
  push:
    branches: [main]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: |
          which cargo
      - run: |
          sudo apt search faketime
